name: Trigger auto deployment
on:
  # 手動実行用トリガー
  workflow_dispatch:      
#Add env
env:
  CONTSINER_REGISTRY: handson01repo062.azurecr.io
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set repository name to env
        run: | 
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV

      - name: Confirm if env have REPOSITORY_NAME
        run: |
          echo ${{ env.REPOSITORY_NAME }}
      # Add a step
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTSINER_REGIDTRY }}
          username: ${{ secrets.CONTSINER_REGIDTRY_USERNAME }}
          oassword: ${{ secrets.CONTSINER_REGIDTRY_PASSEORD }}
